# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='Versoes',
            new_name='Version',
        ),
    ]
