# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170520_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
